### PR TITLE
Add the ability to re-order parties

### PR DESCRIPTION
**Pull request by amoeba**
Closes https://github.com/NCEAS/metacatui/issues/521

As decided in #521, the initial implementation adds simple up/down buttons alongside each party view. Clicking either button moves the party up or down on the page and also updates the underlying EML model so the serialized document reflects the change. When re-ordering creators, the citation preview automatically updates to reflect the changes.

Three things I'd appreciate an extra look at are:

1. I don't let you move a party down below the new/placeholder party so the placeholder is always the last item in the group. It made sense to me to leave the placeholder at the bottom.
2. I didn't wanna to get too fancy with the up/down buttons so I just put them to the left of the party menu. Very much open to feedback here.
3. I wanted to disable the up or down button when it would have no effect (i.e., the Up button would be disabled on the first item) but was having trouble finding a clean way to do it. Right now, you can click the button but it does nothing.

### CODE REVIEW

**Comment by mbjones** [comment]
Awesome, @amoeba.  Can you paste a screenshot in here so we can see the UI layout in action?

**Comment by amoeba** [comment]
Sure:

Here's me reversing the order of three creators:

Kapture 2020-04-16 at 16 25 38

**Comment by laurenwalker** [comment]
Looks great to me, Bryce!! About your 3 items for review: I think that all sounds fine. I was originally imagining the Move Up and Move Down buttons to be options inside the menu next to each party (the menu is accessible via the three vertical dots). But since we have plans to eventually redesign the EMLPartyView anyway (#1238), I think we can keep it as-is for now, unless that's a super quick fix.

Thanks again!

**Comment by amoeba** [comment]
> I was originally imagining the Move Up and Move Down buttons to be options inside the menu next to each party...

Ah, okay. I assumed you wanted literal buttons when you said,

> To start, this feature should use a simple move up/down buttons

I like the buttons being visible without being behind a click since I actually didn't know the three dot button on the right was there until the other day. Putting them there is a super easy change though. Lemme know.

**Comment by laurenwalker** [comment]
I think it's fine as-is

**Comment by mbjones** [comment]
I prefer it as is, where the buttons are more evident.

**Pull request merged**
