### PR TITLE
Fix the NSF award API endpoint

### PR DESCRIPTION
**Pull request by robyngit**
The major part of the fix involved setting up the ADC proxy to point to the new NSF grants API endpoint, then using the proxy in MetacatUI rather than the endpoint directly since it doesn't support CORS. Other minor fixes and improvements made along the way include:

- Remove unused getGrant method from the LookupModel
- Use native fetch API instead of jQuery.ajax to retrieve grants
- Show spinner to indicate that grants are being retrieved (was set up but not used)
- Move some logic from the getGrantAutocomplete method to new, smaller methods
- Add missing JS docs
- Add error handling
- Add a guide to help repos set up their own proxy
- Start tests for the LookupModel, including a test for the getGrants method

### CODE REVIEW

**Comment by robyngit** [comment]
@rushirajnenuji, no rush, but if would you have a chance to give this a quick test to make sure everything's ok? You should only need to set the theme to "arctic" in order for the funding autocomplete field to work in the editor.

**Comment by rushirajnenuji** [comment]
Thank you @robyngit  -- I'll test it out and get back to you.

**Comment by robyngit** [comment]
@rushirajnenuji forgot to point out that I did identify some improvements that are needed to this in the future: https://github.com/NCEAS/metacatui/issues/2243 (just to save you some time in case you come to the same conclusions)

**Review by rushirajnenuji — APPROVED** [review]
Reviewed these changes on my local instance of MetacatUI and they look good. Thank you for getting this fix in @robyngit!

**Comment by robyngit** [comment]
Thanks @rushirajnenuji !

**Pull request merged**
