### PR TITLE
Refactor CitationView and CitationModel

### PR DESCRIPTION
**Pull request by robyngit**
This PR is a refactor of the CitationView & CitationModel, to enable fixing https://github.com/NCEAS/metacatui/issues/264 and to make it easier to complete https://github.com/NCEAS/metacatui/issues/567.

Major changes include:
- The Citation model can populate its attributes from other models used for citations (SolrResult models, DataONEObject models, etc). This means all of the logic that maps other model attributes to citation information occurs in the CitationModel, rather than in the CitationView
- When info is pulled from the metrics service, the citationMetadata attribute is transformed into a nested collection of CitationModels
- The CitationView only renders content directly from the CitationModel
- The HTML layout of the CitationView is now specified in templates, rather than in the view itself
- Different "styles" can be set on the CitationView to specify how the citation should be formatted. Styles are configured as a property of the view, and each style can have a specified set of options, a template, and a special render function.
- Make whitespace/formatting consistent

This PR is a draft because I still need to write unit tests for the Citation Model, and implement a style that allows showing all the authors.

Since the citation view is used extensively throughout MetacatUI, and since there are a lot of changes here, a review at the current stage would be helpful.

@rushirajnenuji I would find it particularly helpful if you could check how the CitationView looks in contexts I may not have thought of. It's hard to find a test case for every situation!

@vchendrix I tagged you because these changes will impact the customization that you described in issue #567, so I thought you might want the opportunity to review it. If you have time and would like to provide feedback at this stage, I would welcome it!

### CODE REVIEW

**Comment by vchendrix** [comment]
@robyngit Thanks for including me in the draft PR! In theory this sounds good.  It is hard for me to tell whether our specific requirements can be met since I am unfamilar with the code. Our specific requirements are below.  Let me know if your new implementation can accomodate this.  @helbashandy  let Robyn know if you  have anything to add to this.

1. The author names should be `<Lastname>, <first initial> <second initial>` and separated by colons
2. we used `project` for the `publisher`
3. we add `accessed via ...` at the end

**ESS-DIVE citation format**
```
<author list> (<pub year>): <dataset title>. <project name>. ESS-DIVE Repository. 
Dataset. <doi> accessed via <link to dataset on essdive> on <today's date>
```

**example of ESS-DIVE citation format**

Hanson P J ; Todd D E ; Riggs J S ; Wolfe M E ; O'Neill E G (2001): Walker Branch Throughfall Displacement Experiment Data Report: Site Characterization, System Performance, Weather, Species Composition, and Growth (NDP-078 and 078A). Carbon Dioxide Information Analysis Center (CDIAC), Oak Ridge National Laboratory (ORNL), Oak Ridge, TN (United States), ESS-DIVE repository. Dataset. [doi:10.3334/CDIAC/VRC.NDP078](https://data.ess-dive.lbl.gov/datasets/doi:10.3334/CDIAC/VRC.NDP078) accessed via https://data.ess-dive.lbl.gov/datasets/doi:10.3334/CDIAC/VRC.NDP078 on 2023-02-10

**Comment by robyngit** [comment]
@rushirajnenuji this PR is ready for review! I've tested in as many cases as I could think of, but I imagine you know of more edge cases when it comes to citations than I do.

@vchendrix and @helbashandy, I added [a guide](https://github.com/NCEAS/metacatui/blob/507ddef54d728aa0cb3e858c915954339a866c8c/docs/guides/themes/citations.md) on customizing citations that should help you display citations in ESS-DIVE format.

**Review by rushirajnenuji — APPROVED** [review]
Hi @robyngit - Thank you for working on this Citations refactor. I went through the code and tested the application to go through all the citation usage/references that I could think of in the application and everything looks great!

**Comment by robyngit** [comment]
Woohoo! Thank you @rushirajnenuji!

**Pull request merged**
