### PR TITLE
New CatalogSearchView with configurable filters & Cesium map

### PR DESCRIPTION
**Pull request by robyngit**
This pull request introduces the new `CatalogSearchView`, set to replace both the `DataCatalogView` and `DataCatalogViewWithFilters` (although these will remain functional but deprecated). The updated catalog view takes advantage of the Filters infrastructure, initially designed for portals, to enable straightforward configuration of repository search filters. Additionally, it transitions from Google Maps to the more versatile Cesium map, which offers a 3D globe representation of the world instead of a 2D projection.

While a few tasks remain, this feature is nearing completion. As such, I am opening this draft pull request to start gathering feedback.

Here's a current snapshot of the `CatalogSearchView` within the ADC:

Screenshot 2023-04-20 at 15 02 10

### CODE REVIEW

**Comment by mbjones** [comment]
Thanks, @robyngit Any sense why the automated tests are failing? Is that expected at this point?

**Comment by robyngit** [comment]
> Thanks, @robyngit Any sense why the automated tests are failing? Is that expected at this point?

@mbjones, yes, it's because I haven't updated the unit tests since I made changes to the models. It's one of the remaining task on [my list](https://github.com/orgs/NCEAS/projects/3/views/1).

**Comment by robyngit** [comment]
@rushirajnenuji this is ready to test when you're ready! I'm doing some testing on my own and also working on writing unit tests and a guide (in docs), but that's no reason to wait on a review.

**Comment by robyngit** [comment]
The latest version, as of the time of writing, is deployed at https://test.arcticdata.io/

**Review by rushirajnenuji — APPROVED** [review]
I tested this PR on my local development instance and the changes look good. I did run into some performance issues (loading latency) but it looks like we already have a ticket for that (https://github.com/NCEAS/metacatui/issues/2145). 

Thank you for working on this feature, this will be a great addition to MetacatUI.

**Pull request merged**
